package com.example.krepagireveshoppinglist.Objects;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;


public class Product extends RealmObject {

    @PrimaryKey
    private String ID;
    private String Name;
    private String Balance;
    private String ToBuy;
    private Category myCategory;
    private boolean isUrgent;

    // Standard getters & setters generated by your IDE…
    public Product(){}

    public Product(String ID, String name, String balance, String toBuy,boolean isUrgent,Category myCategory) {
        this.ID = ID;
        Name = name;
        Balance = balance;
        ToBuy = toBuy;
        this.myCategory=myCategory;
        this.isUrgent=isUrgent;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public Category getMyCategory() {
        return myCategory;
    }

    public void setMyCategory(Category myCategory) {
        this.myCategory = myCategory;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }

    public String getBalance() {
        return Balance;
    }

    public void setBalance(String balance) {
        Balance = balance;
    }

    public String getToBuy() {
        return ToBuy;
    }

    public void setToBuy(String toBuy) {
        ToBuy = toBuy;
    }

    @Override
    public String toString() {
        return Name;
    }

    public boolean isUrgent() {
        return isUrgent;
    }

    public void setUrgent(boolean urgent) {
        isUrgent = urgent;
    }
}
